

- hosts: datadog.shadowman.dev
  vars:
    invalid_directive: "FOO"
  tasks:
  - name: Review and correct the httpd.conf file
    ansible.builtin.lineinfile:
      path: /etc/httpd/conf/httpd.conf
      line: '{{ invalid_directive }}'
      state: replaced
      backup: yes

  - name: Check for syntax errors
    ansible.builtin.command:
      cmd: "httpd -t"
    register: httpd_check

  - name: Restart Apache HTTP Server
    ansible.builtin.systemd:
      name: httpd
      state: restarted
      enabled: yes

  - name: Monitor system logs
    ansible.builtin.debug:
      var: httpd_check.stdout_lines
...
