---
- name: Play to demonstrate task delegation
  hosts: datadog.shadowman.dev
  tasks:
    - name: Check Apache configuration for errors
      ansible.builtin.command: apachectl -t
      become: true
      delegate_to: "{{ item }}"
      loop: "{{ inventory_hostname |flatten(levels=1) }}"
    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted
      become: true
      delegate_to: "{{ item }}"
      loop: "{{ inventory_hostname |flatten(levels=1) }}"
