-   name: fix and restart httpd
    hosts: datadog
    tasks:
    -   name: fix and restart httpd
        ansible.builtin.lineinfile:
            path: /etc/httpd/conf/httpd.conf
            regexp: ^\s*InvalidDirectiveHere
            state: absent
    -   name: restart httpd
        ansible.builtin.service:
            name: httpd.service
            state: restarted
