

- name: Check and correct httpd.conf
  hosts: datadog.shadowman.dev
  vars:
    httpd_conf_path: /etc/httpd/conf/httpd.conf
  tasks:
    - name: Review httpd.conf file and identify the invalid directive on line 35
      ansible.builtin.shell: 'grep ^ #line 35 {{ httpd_conf_path }}'
      register: httpd_config_error

    - name: Correct the spelling or ensure the directive is properly included
      ansible.builtin.lineinfile:
        path: "{{ httpd_conf_path }}"
        line: "# directive corrected"
        insertbefore: "^# line 35"
      when: httpd_config_error.stdout_lines | length > 0

    - name: Test httpd.conf file for syntax errors
      ansible.builtin.shell: "httpd -t"
      register: httpd_syntax_check
      changed_when: "'Syntax' in httpd_syntax_check.stdout"

    - name: Restart Apache HTTP Server
      ansible.builtin.systemd:
        name: httpd
        state: restarted
      when: httpd_syntax_check.rc == 0

- name: Monitor system logs for any further errors or issues
  hosts: datadog.shadowman.dev
  vars:
    journalctl_filters:
      - module: kernel
      - module: cron
    journalctl_options: "--since '1 hour ago'"
  tasks:
    - name: Display system logs
      ansible.builtin.shell: "journalctl {{ journalctl_filters | join(' ') }} {{ journalctl_options }}"
      register: system_logs
      failed_when: system_logs.stdout_lines | length > 0

