-   name: copy httpd.conf file
    hosts: datadog.shadowman.dev
    tasks:
    -   name: copy httpd.conf file
        ansible.builtin.copy:
            src: files/httpd.conf
            dest: /etc/httpd/conf/httpd.conf
    -   name: restart httpd service
        ansible.builtin.service:
            name: httpd
            state: restarted
