-   name: copy httpd.conf file
    hosts: datadog.shadowman.dev
    tasks:
    -   name: copy httpd.conf
        ansible.builtin.copy:
            src: files/httpd.conf
            dest: /etc/httpd/conf/httpd.confg
