-   name: remove line in file
    hosts: datadog
    tasks:
    -   name: remove line in file
        ansible.builtin.lineinfile:
            path: /etc/httpd/conf/httpd.conf
            regexp: InvalidDirectiveHere
            state: absent
