

- name: Review and correct httpd.conf file on datadog.shadowman.dev
  hosts: datadog.shadowman.dev
  become: yes
  tasks:
    - name: Review httpd.conf file
      ansible.builtin.slurp:
        src: /etc/httpd/conf/httpd.conf
      register: httpd_conf_content

    - name: Identify invalid directive on line 35
      ansible.builtin.set_fact:
        invalid_directive: "{{ (httpd_conf_content.content | string) | position('\\n', 34) }}"
      when: invalid_directive is defined

    - name: Correct spelling or ensure directive is properly included in the server configuration
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        line: "{{ invalid_directive }}"
        state: present
        create: yes
        backup: yes
      when: invalid_directive

    - name: Test httpd.conf file for syntax errors
      ansible.builtin.command: httpd -t
      register: httpd_test_result
      changed_when: httpd_test_result.stdout.find('Syntax OK') == -1

    - name: Restart the Apache HTTP Server
      ansible.builtin.service:
        name: httpd
        state: restarted
      when: httpd_test_result.stdout.find('Syntax OK') == -1

    - name: Monitor system logs for errors
      ansible.builtin.command: tail -n 10 /var/log/httpd/error.log
      register: error_log_output
      when: httpd_test_result.stdout.find('Syntax OK') == -1
...
