---
- name: correct an invalid apache directive
  hosts: datadog
  tasks:
    - name: correct an invalid apache directive
      ansible.builtin.replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: ^InvalidDirectiveHere
        replace: ValidDirective
    - name: restart apache
      ansible.builtin.service:
        name: httpd
        state: restarted
