-   name: fix and restart httpd
    hosts: datadog.shadowman.dev
    tasks:
    -   name: fix httpd
        ansible.builtin.replace:
            path: /etc/httpd/conf/httpd.conf
            regexp: (Syntax error on line [0-9]*. Apache is not running.)
            replace: ''
    -   name: restart httpd
        ansible.builtin.service:
            name: httpd
            state: restarted
