-   name: fix and restart httpd
    hosts: datadog.shadowman.dev
    tasks:
    -   name: fix and restart httpd
        ansible.builtin.lineinfile:
            path: /etc/httpd/conf/httpd.conf
            regexp: ^\s*InvalidDirectiveHere
            state: absent
    -   name: restart httpd
        ansible.builtin.service:
            name: httpd
            state: restarted
