

- hosts: datadog.shadowman.dev
  become: yes
  tasks:
    - name: Review httpd.conf file
      command: cat /etc/httpd/conf/httpd.conf
      register: httpd_conf_output

    - name: Identify invalid directive
      set_fact:
        syntax_error_line: "{{ httpd_conf_output.stdout_lines |
            select('search', '"invaliddirective"'|default('')) | first }}"

    - name: Correct the directive
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        line: "InvalidDirective"
        create: yes
        state: present

    - name: Test httpd.conf for syntax errors
      command: httpd -t
      register: httpd_syntax_check
      failed_when: httpd_syntax_check.stdout_lines[0] != "Syntax OK"

    - name: Restart Apache HTTP Server
      command: systemctl restart httpd
      when: httpd_syntax_check.stdout_lines[0] != "Syntax OK"

    - name: Monitor system logs
      lineinfile:
        path: /var/log/httpd/error_log
        line: "^.*Error.*$"
        state: present
      register: log_changes

    - name: Display system logs
      command: cat /var/log/httpd/error_log
      when: log_changes.changed
