:
- hosts: datadog.shadowman.dev
  tasks:
    - name: Copy file
      ansible.builtin.copy:
        src: files/httpd.conf
        dest: /usr/local/apache2/conf/httpd.conf
    - name: Restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted
      notify:
        - restart Apache
...

- hosts: datadog.shadowman.dev
  tasks:
    - name: Copy file
      ansible.builtin.copy:
        src: files/httpd.conf
        dest: /usr/local/apache2/conf/httpd.conf

    - name: Restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted
      notify:
        - restart Apache
