
- hosts: datadog.shadowman.dev
  become: yes
  tasks:
    - name: Copy httpd.conf to location
      copy:
        src: httpd.conf
        dest: /etc/httpd/conf/httpd.conf

    - name: Restart httpd service
      service:
        name: httpd
        state: restarted
