-   name: Fix the httpd service
    hosts: datadog.shadowman.dev
    tasks:
    -   name: Fix the httpd service
        ansible.builtin.replace:
            path: /etc/httpd/conf/httpd.conf
            regexp: ^(\s+)(InvalidDirectiveHere)(\s+.*)$
            replace: \1\2\3
