---
- name: correct invalid directive
  hosts: datadog.shadowman.dev
  tasks:
    - name: correct invalid directive
      ansible.builtin.replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: InvalidDirectiveHere
        replace: ValidDirective
    - name: restart service httpd
      ansible.builtin.service:
        name: httpd
        state: restarted
