---
- name: Check if service is running
  check_mode: true
  ansible.builtin.systemd_service:
    state: started
    name: "{{ service_issue }}"
  register: service_status

- name: Check if service is running
  ansible.builtin.debug:
    msg: "{{ service_status }}"

- name: Check if service is running
  ansible.builtin.debug:
    msg: "{{ service_status.status.ActiveState if service_status.status.ActiveState is defined else 'ActiveState not found' }}"

- name: Retrieve last 20 lines of service logs
  ansible.builtin.command: journalctl -u {{ service_issue }}.service -n 20
  register: service_logs
  ignore_errors: true
  when: service_status.changed

- name: Store service logs as a variable
  ansible.builtin.set_fact:
    service_log_output: "{{ service_logs.stdout }}"
  when: service_status.changed

- name: Display service logs
  ansible.builtin.debug:
    msg: "{{ service_log_output }}"
  when: service_status.changed

- name: Set stats for next controller job
  ansible.builtin.set_stats:
    data:
      gpt_prompt: "\n\n### Instructions:\nI would like a summary of the root cause of an issue on our RHEL Linux server with the {{ service_issue }} service. Here are recent error logs: {{ service_log_output }} \n\n### Response:\n"
      max_tokens: 2000
  when: service_status.changed
