---
- name: Send POST request using uri module to get RCA response
  ansible.builtin.uri:
    url: "{{ ai_url }}/v1/chat/completions"
    method: POST
    headers:
      accept: "application/json"
      Content-Type: "application/json"
      Authorization: "Bearer {{ api_token }}"
    body:
      response_format:
        type: json_object
      messages:
        - 'role': 'system'
          'content': '{{ prompt }}'
      model: "{{ ai_model }}"
      max_tokens: "{{ max_tokens | default('500') }}"
      temperature: 0
    body_format: json
    return_content: true
    status_code: 200
    timeout: 60
  register: response

- name: Set AI Response
  ansible.builtin.set_fact:
    ai_response: "{{ response.json.choices[0].message.content | default('No response') }}"

- name: Check if response is JSON and retrieve text
  ansible.builtin.debug:
    msg: "{{ ai_response }}"
    