---
- name: Get current CPU usage
  ansible.builtin.command: top -b -n 1 -w512
  changed_when: false
  register: cpuusage

- name: Set stats for next controller job
  ansible.builtin.set_stats:
    data:
      service_log_output: "\"{{ cpuusage.stdout }}\""
      max_tokens: 2000
